### PR TITLE
feat: add a config prop 'aggressiveFollowUps' to follow up based on priority

### LINKED ISSUE #26: Priority Speed
Divide the config timeouts by the priority level. This makes follow ups more aggressive based on the priority level. 

`Priority: 5 (Emergency)` Means divide by 5. 

- warning = 3.5 days / 5 = 16.8 hours
-  disqualify = 7 days / 5 = 33.6 hours

Should be configurable (priority enabled: Boolean)

### PR DESCRIPTION
**Pull request by ishowvel**
Resolves #26

### CODE REVIEW

**Comment by 0x4007** [comment]
Also a QA test or prove that it works is necessary.

**Comment by ishowvel** [comment]
ill remake the pr

**Comment by ishowvel** [comment]
god setting up the kernel and plugins is hard

**Comment by 0x4007** [comment]
> god setting up the kernel and plugins is hard

@gentlementlegen @whilefoo  can you guys fix this with better docs

**Pull request closed without merging**
