### PR TITLE
Create manifest.json

### PR DESCRIPTION
**Pull request by 0x4007**
I just copied it over from `development`

### CODE REVIEW

**Comment by gentlementlegen** [comment]
I think you should just merge development into main? Why is it from your own branch?

**Comment by 0x4007** [comment]
Because I added a new file from the GitHub ui

**Comment by gentlementlegen** [comment]
@0x4007 Then please amend your commit so it respects conventional commit naming, and then you can merge.

**Comment by 0x4007** [comment]
> I think you should just merge development into main? Why is it from your own branch?

https://github.com/ubiquity-os-marketplace/daemon-disqualifier/pull/28

**Pull request closed without merging**
